### ISSUE TITLE
Implementar Recursive Backtracker

### ISSUE THREAD

**Issue by skatrak** [MazeSolver/MazeSolver#37]
Crear un agente que intente realizar un recorrido en profundidad del laberinto para encontrar la salida. Se puede partir del agente *Hill Climbing*, porque es un caso especial en el que la dirección de movimiento se elige sin utilizar ninguna función heurística.

Este agente inherentemente no conlleva ninguna configuración, así que el panel de configuración que tendría sería un solo `JLabel` que indicara que el agente no se puede configurar.

**Comment by kevinrobayna** [comment]
Ya puse eso, el método look(Direction) es el best method eu xD

Mira a ver si lo de la ventana de configuración esta como lo que tu pusiste del label y tal

P.D Gz tu forma de programar es flipante, cuesta verlo al principio pero.. joder como facilita las cosas el royo del backtracking y demas si la dirección es NONE y tal genial la verdad. @skatrak

**Comment by skatrak** [comment]
Ahora no puedo ejecutarlo, pero si funciona bien habiendo interacción entre varios agentes en un entorno y la "interfaz de configuración" se ve razonablemente bien, lo puedes meter ya en master y cuando pueda lo pruebo yo también.
