### ISSUE TITLE
Release de v1.0

### ISSUE THREAD

**Issue by kevinrobayna** [MazeSolver/MazeSolver#44]
Deberíamos crear una realease 1.0 con lo que tenemos actualmente para poner un link ahí de descarga y demas. No crees? @skatrak

**Comment by skatrak** [comment]
Lo que hay en el repo no sería lo que un usuario se querría descargar, pero supongo que habría que hacerlo para marcar que esta es la primera versión "estable" del programa.
Tenemos que buscar otro sitio donde subir los `.jar` de cada versión del programa (en el peor caso podemos dedicar una página del blog a eso).
