### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by kevinrobayna** [MazeSolver/MazeSolver#45]
Realizar una wiki explicando la interfaz

**Comment by kevinrobayna** [comment]
hecho https://github.com/MazeSolver/MazeSolver/wiki/Tutorial-sobre-la-GUI

**Comment by skatrak** [comment]
¿No se suponía que había que revisarlo los dos antes de subirlo? Iba a hacerlo esta tarde...

**Comment by kevinrobayna** [comment]
ah ya ya, pero como no dabas señales de vida pense que estabas en el sureto sin internet xD

**Comment by skatrak** [comment]
Y lo estaba, pero yo sé cuáles son las fechas hombre.

**Comment by kevinrobayna** [comment]
yo no muy bien xD por eso lo hice xD Cuando empezaban a corregir?

**Comment by skatrak** [comment]
El 1 de Abril (este miércoles).
