### ISSUE TITLE
Traducciones?

### ISSUE THREAD

**Issue by kevinrobayna** [MazeSolver/MazeSolver#46]
Vi una libreria llamada c10n https://github.com/rodionmoiseev/c10n que para lo de tr("string") de qt usa interfaces de java, y despues a la hora de querer usarla la "compilas" en esa clase, es decir puedes tener 1231 interfaces (que pueden ir heredando unas de otras) y en una determinada clase usas una determinada. La verdad esta bastante guay, yo estube probando y funciona genial. Además le hice un pull request a la libreria para soportar el español como configuración por defecto sin poner cosas xD

De momento hice la prueba con el gui y le puse inglés y español pero vamos la idea sería tenerlo todo. Además de los errores y demas que me encargaría yo de hacerlo tan pronto me digas que te parece. Yo lo veo guay ya que podríamos abrir issues para que la gente añada traducciones a los idiomas suyos.

para probar si funciona o no ejecuta el jar con estos parametros a java

java -Duser.language=idioma

y así vas cambiando el idioma, por defecto esta puesto para que si tu idioma no esta en las interfaces se use inglés. Y vamos si alguien añade uno que la propia librería no soporte pues se añaden a la configuración o simplemente pull request y ya xD

P.D: Mi idea es que se cambie el idioma al ejecutar el MazeSolver, no que puedas ir cambiando en ejecución

P.P.D Obviamente la licencia de esta libreria es libre es Apache que vamos esta reconocida por gnu como libre.

**Comment by kevinrobayna** [comment]
P.P.P.D mira lo que te dije en la rama translation xD esta muy guay

**Comment by skatrak** [comment]
En su momento intenté ver cómo hacer las traducciones, pero con las clases estándar de Java. Es verdad que esa librería lo deja todo mucho más fácil, pero tengo que decirte que si vamos a meter traducciones lo suyo sería cargarlas de ficheros y además que se pudiera cambiar el idioma en tiempo de ejecución.

Por lo que he visto, la librería permite cargar traducciones de ficheros y decidir la localización (idioma) de los strings en tiempo de ejecución, pero tenemos que restructurar la aplicación. El caso es que tendríamos que separar en cada clase un método en el que se asignaran los textos de cada cosa y forzar su ejecución cada vez que se cambie la localización.

Cómo hacerlo (idea):
```java
// LocaleChangeListener.java
public interface LocaleChangeListener {
  public void onLocaleChanged();
}
```
```java
// MainWindow.java
public class MainWindow extends JFrame implements LocaleChangeListener {
  // ...
  public void onLocaleChanged() {
    m_itm_maze_clone.setText(_trGUI.copyMaze() + "...");
    // ...
  }
}
```
Claro, que cada ventana que tuviera "sub-ventanas" tendría tener una lista de `LocaleChangeListener` a las que tendría que notificar en `onLocaleChanged()`.

Eso sí, los nombres de los algoritmos de creación de laberintos y los nombres de los agentes los tenemos que dejar en inglés, porque hay mapeos String-Clase y eso no se puede cambiar en tiempo de ejecución sin cambios significativos.

**Comment by skatrak** [comment]
Voy a intentar implementarlo con las traducciones en código. Luego te aviso y ya tú lo adaptas para que se lea desde resource bundles.

**Comment by kevinrobayna** [comment]
Hmm okay, avísame entonces

**Comment by skatrak** [comment]
Las traducciones están puestas ya, y está todo montado para que se puedan actualizar en tiempo de ejecución con tan sólo llamar `MainWindow.translate()`. Hay un par de cosas que no puse para traducir, pero en general está lo importante todo puesto.

Si quieres implementa tú el menú de idiomas, que cambie lo que tenga que cambiar de la librería y que llame al método que te dije.

**Comment by kevinrobayna** [comment]
Okay! Me pongo a ello.

**Comment by kevinrobayna** [comment]
Ya esta puesto para traducir desde un menú, además añadi las traducciones de los resultados de la simulación. Ahora intentaré introducir los resource bundle, pero vamos mejor tener esto ya así encaminado que la entrega del CUSL esta a la vuelta de la esquina.

**Comment by skatrak** [comment]
Vale, cierro este issue y abro otro específico para poner las traducciones en resource bundles.

P.D: Por favor, deja de meterle formato automático a los ficheros, que luego quedan líneas malamente divididas por la mitad, como en (true story xD):
```java
JOptionPane.showMessageDialog(null, s_tr.message().noEnvironmentSelected(), s_tr
  .message().fileSaveFailed(), JOptionPane.WARNING_MESSAGE);
```
Y como hagas eso en una rama mientras yo trabajo en otra los conflictos van a estar guapísimos. Formatear bien sí, pero tampoco hay que pasarse, que eso es menos legible de como estaba antes. A lo mejor es que soy medio rarito yo o algo...
