### ISSUE TITLE
Mover las traducciones a ficheros separados

### ISSUE THREAD

**Issue by skatrak** [MazeSolver/MazeSolver#47]
Supuestamente la librería que utilizamos para la localización de strings soporta la lectura de esas cadenas desde resource bundles de java.

Lo suyo sería que estos resource bundles fueran incluidos en el .jar de la aplicación, para que fueran transparentes para el usuario.

**Comment by kevinrobayna** [comment]
viendo como funciona la localización desde fichero con los resourcebundle de java,
``` Java
msg.get("Run");
```
Que poner la cadena que actua como clave. No crees que sigue siendo mejor con las interfaces? ya que es la principal ventaja de la libreria. Lo sigue permitiendo pero no deja de ser el tipico uso de java con los resourcebundle.

**Comment by kevinrobayna** [comment]
ale hecho xD no habia hecho tanto copy pasterino en toda mi vida xD Cuando tal ponlo en la rama master
