### ISSUE TITLE
Actualizar las traducciones

### ISSUE THREAD

**Issue by skatrak** [MazeSolver/MazeSolver#57]
- [x] [Francés](https://github.com/MazeSolver/MazeSolver/blob/master/resources/translations/Translations_fr.properties)
- [x] [Ruso](https://github.com/MazeSolver/MazeSolver/blob/master/resources/translations/Translations_ru.properties)
- [x] [Alemán](https://github.com/MazeSolver/MazeSolver/blob/master/resources/translations/Translations_de.properties)
- [ ] ... más

**Comment by kevinrobayna** [comment]
añadida la traducción a alemán en c0fc87dc2813fa6d38d2c1ee9bd7073cb50881b7
