### ISSUE TITLE
Guardado / Carga de entornos y posiciones de los agentes

### ISSUE THREAD

**Issue by kevinrobayna** [MazeSolver/MazeSolver#66]
Hablando con usuario de MazeSolver que esta asistiendo a las clases de Sistemas Inteligente de la ULL me comentó que cuando se tienen muchos agentes para repetir las simulaciones con el estado inicial (justo el que se tiene antes de empezar la simulación ó se me ocurre que se pueda guardar un estado al que se quiera volver en el GUI) es un fastidio estar moviendo a cada agente a la posición donde lo tenias al principio.

Esto yo creo que tiene su utilidad aunque sólo cuando quieres probar los resultados con agentes empezando en el mismo lugar pero cambiando su configuración. Donde tiene mas sentido es en los agentes de situación-acción o tablas de percepción-acción debido a que te interesa ver el comportamiento de un número muy grande de agentes.

Supongo que el estado inicial solo se refiere a la posición de los agentes en el laberinto y no la configuración de cada uno.

Uno de las cosas a tener en cuenta es que pasa cuando eliminas un agente, ¿se descarta el estado inicial? o simplemente se elimina de dicho agente los agentes que se hayan eliminado.

Se debería añadir un botón para guardar, descartar y restaurar el estado de los agentes pero no creo que sea necesario poder exportar dicho estado.

¿Qué te parece esto a ti @skatrak ?

**Comment by kevinrobayna** [comment]
Se debería añadir un botón para guardar, descartar y restaurar el estado de los agentes pero no creo que sea necesario poder exportar dicho estado.

**Comment by skatrak** [comment]
Lo que pienso es que es algo que tarde o temprano habría que implementar, pero sobre la forma de hacerlo yo pienso que la mejor manera de hacerlo sería la siguiente:
- En el menú "Entorno" añadir opciones de "Guardar entorno" y "Cargar entorno". Estas opciones deberían, a través de un fichero, permitir almacenar y recuperar las posiciones y configuraciones de los agentes, junto al laberinto asociado al entorno.
- En el menú "Entorno" también añadir las opciones "Tomar instantánea" y "Recuperar instantánea". La primera almacenaría sólo las posiciones de los agentes en el entorno seleccionado y la otra los volvería a colocar donde estaban cuando se tomó la última instantánea. "Recuperar instantánea" sólo debería funcionar si no se han creado ni eliminado agentes desde que se tomó la instantánea y si no se ha modificado el laberinto o, al menos, no ha cambiado el tamaño.
- Al cargar un entorno, que se tome una instantánea por defecto.
- No creo que ni siquiera hiciera falta un botón de "Descartar instantánea", porque realmente no te molesta haber hecho una aunque no la uses más.

A mí me parece que esta sería la mejor solución. Es importante poder guardar los entornos para poder reproducir ciertos comportamientos que hayas observado.

**Comment by kevinrobayna** [comment]
Me parece la forma correcta también la verdad.
> En el menú "Entorno" añadir opciones de "Guardar entorno" y "Cargar entorno". Estas opciones deberían, a través de un fichero, permitir almacenar y recuperar las posiciones y configuraciones de los agentes, junto al laberinto asociado al entorno.
Guardando y cargando el entorno te aseguras de que puedes exportarlo a otro ordenador para ya sea compartirlo o que te corrija un profesor.

> En el menú "Entorno" también añadir las opciones "Tomar instantánea" y "Recuperar instantánea". La primera almacenaría sólo las posiciones de los agentes en el entorno seleccionado y la otra los volvería a colocar donde estaban cuando se tomó la última instantánea. "Recuperar instantánea" sólo debería funcionar si no se han creado ni eliminado agentes desde que se tomó la instantánea y si no se ha modificado el laberinto o, al menos, no ha cambiado el tamaño.
Exacto. Yo creo que siempre y cuando sólo modifique la configuración de los agentes la instantánea debe ser la misma. Y en caso de modificar cualquier otra cosa pues que se cree una nueva instantánea.
> Al cargar un entorno, que se tome una instantánea por defecto.
Sep, es el comportamiento que yo esperaría.
