### ISSUE TITLE
Añadir test

### ISSUE THREAD

**Issue by kevinrobayna** [MazeSolver/MazeSolver#71]
Estaría bastante bien añadir tests a la plataforma, en varias entrevistas que he tenido y han visto este proyecto me han preguntado porque no hay ningún test? Así que en vista de hacer mas profesional y hacer mas fácil la colaboración se deberían añadir algunos test (unit test y integration test) para comprobar que las funciones hacen lo que se espera y que el sistema entero funciona (que los agentes encuentren la salida por ejemplo)

Para ejecutar los test se podría usar Travis y así comprobamos que mazesolver funciona en varias jdk (openjdk oraclejdk) además de las distintas versiones de java (java7, java8, no creo que funcione en java6 porque casi nada lo hace ya xD)

**Comment by skatrak** [comment]
No funciona ni en Java 7, usamos cosas de la API Java 8. ¿Alguna idea de qué tipo de tests se podría poner? Lo de los tests es un tormento si no se hace desde el principio, como es este caso.

**Comment by kevinrobayna** [comment]
El fin de semana preparo una lista de las cosas que yo testearía. Lo que hay que tener en cuenta es que obviamente hay cosas que sabemos que funcionan pero el objetivo de los unit test no es saber que algo funciona si no que en el futuro si alguien hace un cambio pues que sepa que no ha roto nada (por eso lo te travis para que él y todo el mundo en github vea que ese commit paso los test o no xD) Pero vamos yo lo que intentaría es testear todo y conseguir un porcentaje alto de code coverage.
